import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const ROOT_DIR = path.resolve(__dirname, "..");
const APP_DIR = path.join(ROOT_DIR, "app");
const OUTPUT_PATH = path.join(ROOT_DIR, "lib/generated/utilities-index.ts");

interface UtilityManifestFile {
  slug: string;
  importName: string;
}

function toPascalCase(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

function getUtilityManifestFiles(): UtilityManifestFile[] {
  const directories = fs
    .readdirSync(APP_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => !name.startsWith("(") && !name.startsWith("_"));

  const manifests = directories
    .filter((slug) => fs.existsSync(path.join(APP_DIR, slug, "manifest.ts")))
    .map((slug) => ({
      slug,
      importName: `manifest${toPascalCase(slug)}`,
    }))
    .sort((a, b) => a.slug.localeCompare(b.slug));

  return manifests;
}

function buildIndexFile(manifests: UtilityManifestFile[]): string {
  const imports = manifests
    .map(
      ({ slug, importName }) => `import ${importName} from "@/app/${slug}/manifest";`
    )
    .join("\n");

  const manifestArray = manifests.map(({ importName }) => `  ${importName},`).join("\n");

  return `/* This file is auto-generated by scripts/generate-utilities-index.ts */
import type { UtilityManifest } from "@/lib/utilities/types";
${imports}

export const utilities = [
${manifestArray}
] as const satisfies readonly UtilityManifest[];

export const utilitiesById = new Map(utilities.map((utility) => [utility.id, utility]));
export const utilitiesBySlug = new Map(utilities.map((utility) => [utility.slug, utility]));
`;
}

function writeIndexFile(): void {
  const manifests = getUtilityManifestFiles();

  if (manifests.length === 0) {
    throw new Error("No utility manifests found in app/*/manifest.ts.");
  }

  const fileContent = buildIndexFile(manifests);
  const currentContent = fs.existsSync(OUTPUT_PATH)
    ? fs.readFileSync(OUTPUT_PATH, "utf8")
    : "";

  if (fileContent === currentContent) {
    return;
  }

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, fileContent, "utf8");
}

async function watchAndGenerate(): Promise<void> {
  const { watch } = await import("chokidar");
  writeIndexFile();
  console.log("utilities index generated");

  const watcher = watch(path.join(APP_DIR, "*/manifest.ts"), {
    ignoreInitial: true,
  });

  watcher.on("all", (eventName, changedPath) => {
    writeIndexFile();
    console.log(`utilities index regenerated (${eventName}: ${path.basename(changedPath)})`);
  });
}

const watchMode = process.argv.includes("--watch");

if (watchMode) {
  watchAndGenerate().catch((error) => {
    console.error(error);
    process.exit(1);
  });
} else {
  try {
    writeIndexFile();
    console.log("utilities index generated");
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}
